[package]
name_res = "@Strings.AppName"
package_type = "app"
icon_resource = "@Drawables.LauncherIcon"
main_class = "WheelLogCompanionApp"
app_type = "watch-app"
min_sdk = "1.2.0"

[package_meta]
id = "487e6172-972c-4f93-a4db-26fd689f935a"
name = "WheelLog"
version = "3.0.0"
devices = [
    "enduro",
    "fr230",
    "fr235",
    "fr245",
    "fr245m",
    "fr630",
    "fr645",
    "fr645m",
    "fr745",
    "fr935",
    "fr945",
    "fr945lte",
    "fenix3",
    "fenix3_hr",
    "fenix5",
    "fenix5plus",
    "fenix5x",
    "fenix5s",
    "fenix5splus",
    "fenix6",
    "fenix6pro",
    "fenix6s",
    "fenix6spro",
    "fenix6xpro",
    "fenixchronos",
    "vivoactive3",
    "vivoactive3d",
    "vivoactive3m",
    "vivoactive3mlte",
    "vivoactive4",
    "vivoactive4s",
    "approachs60",
    "approachs62",
    "marqadventurer",
    "marqathlete",
    "marqaviator",
    "marqcommander",
    "marqdriver",
    "marqexpedition",
    "marqgolfer",
    "descentmk1",
    "descentmk2",
    "descentmk2s",
    "venu",
    "venu2",
    "venu2s",
    "venud"
]
permissions = [
    "Communications"
]
languages = [
    "eng",
    "rus",
    "ukr",
]

[build]
enable_code_analysis_on_build = false
connect_iq_version = "4.0.3"
signing_key = "id_rsa_garmin.der"
compiler_args = ""

[dependencies]
"BGFX" = ["0.1.0", "BGFX-0.1.0.barrel"]