name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Download & Install ConnectIQ SDK
      run: brew install --cask connectiq

    - name: ls
      run: ls ~ -R -a

    - name: Copy device profiles to ConnectIQ SDK devices folder
      run: mkdir ~/Library/Application\ Support/Garmin/ConnectIQ/Devices && mv -rf ci/fenix3 ~/Library/Application Support/Garmin/ConnectIQ/Devices

    - name: Generate dev key
      run: make generate-devkey

    - name: Build
      run: make build