name: App Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: nkarmanet/monkeyc
    steps:
      - uses: actions/checkout@v2

      - name: Build app
        run: make build
